# Generated by Django 4.0.4 on 2022-04-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('country', models.CharField(choices=[('ADDIS ABABAB', 'ADDIS ABABA'), ('BAHIR DAR', 'BAHIR DAR'), ('HAWASSA', 'HAWASSA')], max_length=20)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
    ]
