# Generated by Django 4.0.4 on 2022-04-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0004_rename_jobseekerprofile_applicant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='ApplicantsRegisteration',
        ),
    ]
